### PR TITLE
Made some tiny tweaks to the podspec so it will work with CocoaLumberjack 2.2

### PR DESCRIPTION
**Pull request by kcalmes**
This will of course need to be submitted to the master spec repo as well. I also adjusted the version, it was not updated in the podspec the last time the repo was tagged.

### CODE REVIEW

**Comment by waltflanagan** [comment]
I tried to push it a few days ago and it did not lint correctly locally.  I haven't had time to investigate why.  I'll try to get to it tonight

**Comment by williamsjj** [comment]
Much appreciated.

**Comment by waltflanagan** [comment]
I had to rev to 2.0.3 because there was already a 2.0.2 out there.  Pushed to cocoapods.  Reminder, this still only works when using cocoapods via libraries, not frameworks.

**Comment by kcalmes** [comment]
I should have thought about that, my mistake.

**Pull request merged**
