### PR TITLE
Update CocoaLumberjack dependency version to 3.x

### PR DESCRIPTION
**Pull request by k06a**
Not tested yet

### CODE REVIEW

**Comment by k06a** [comment]
Looks like it can be compiled with CocoaLumberjack 3.0.0 without any warnings and errors.

**Comment by k06a** [comment]
Why not to merge?

**Comment by k06a** [comment]
Or it should have a new major version too? 3.0.0?

**Comment by waltflanagan** [comment]
I should have time to look at this and publish to trunk this afternoon.  Thanks for the PR

**Comment by waltflanagan** [comment]
I updated the repo to depend on CocoaLumberjack 3.0 and revved the version of this library to 3.0.  

I'm running into some issues pushing to Trunk right now, so in the meantime, you can add `:git => git@github.com:TechSmith/CrashlyticsLumberjack.git`  to the CrashlyticsLumberjack line of your podfile to pull straight from here.

**Pull request closed without merging**
